# This is a fake Dockerfile.

# Those vars are used broadly outside this very Dockerfile
# Github Action CI and release script (./utility.sh) is consuming variables from here.

ARG VERSION="notset"
ARG APP_NAME="notset"
ARG GIT_PROJECT_NAME="notset-in-docker"
#
ARG ALPINE_VERSION="3.10"
ARG USER="notset"
#
ARG DOCKERHUB_USER="devmtl"
ARG GITHUB_USER="firepress"
ARG GITHUB_ORG="firepress-org"
ARG GITHUB_REGISTRY="registry"

